package com.applovin.impl;

import com.applovin.impl.adview.AppLovinTouchToClickListener;
import com.applovin.mediation.MaxAdFormat;
import com.applovin.sdk.AppLovinAdSize;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import org.json.mediationsdk.utils.IronSourceConstants;

/* JADX INFO: loaded from: classes.dex */
public class sj implements Comparable {
    public static final sj A;
    public static final sj A0;
    public static final sj A1;
    public static final sj A2;
    public static final sj A3;
    public static final sj A4;
    public static final sj A5;
    public static final sj A6;
    public static final sj B;
    public static final sj B0;
    public static final sj B1;
    public static final sj B2;
    public static final sj B3;
    public static final sj B4;
    public static final sj B5;
    public static final sj B6;
    public static final sj C;
    public static final sj C0;
    public static final sj C1;
    public static final sj C2;
    public static final sj C3;
    public static final sj C4;
    public static final sj C5;
    public static final sj C6;
    public static final sj D;
    public static final sj D0;
    public static final sj D1;
    public static final sj D2;
    public static final sj D3;
    public static final sj D4;
    public static final sj D5;
    public static final sj E;
    public static final sj E0;
    public static final sj E1;
    public static final sj E2;
    public static final sj E3;
    public static final sj E4;
    public static final sj E5;
    public static final sj F;
    public static final sj F0;
    public static final sj F1;
    public static final sj F2;
    public static final sj F3;
    public static final sj F4;
    public static final sj F5;
    public static final sj G;
    public static final sj G0;
    public static final sj G1;
    public static final sj G2;
    public static final sj G3;
    public static final sj G4;
    public static final sj G5;
    public static final sj H;
    public static final sj H0;
    public static final sj H1;
    public static final sj H2;
    public static final sj H3;
    public static final sj H4;
    public static final sj H5;
    public static final sj I;
    public static final sj I0;
    public static final sj I1;
    public static final sj I2;
    public static final sj I3;
    public static final sj I4;
    public static final sj I5;
    public static final sj J;
    public static final sj J0;
    public static final sj J1;
    public static final sj J2;
    public static final sj J3;
    public static final sj J4;
    public static final sj J5;
    public static final sj K;
    public static final sj K0;
    public static final sj K1;
    public static final sj K2;
    public static final sj K3;
    public static final sj K4;
    public static final sj K5;
    public static final sj L;
    public static final sj L0;
    public static final sj L1;
    public static final sj L2;
    public static final sj L3;
    public static final sj L4;
    public static final sj L5;
    public static final sj M;
    public static final sj M0;
    public static final sj M1;
    public static final sj M2;
    public static final sj M3;
    public static final sj M4;
    public static final sj M5;
    public static final sj N;
    public static final sj N0;
    public static final sj N1;
    public static final sj N2;
    public static final sj N3;
    public static final sj N4;
    public static final sj N5;
    public static final sj O;
    public static final sj O0;
    public static final sj O1;
    public static final sj O2;
    public static final sj O3;
    public static final sj O4;
    public static final sj O5;
    public static final sj P;
    public static final sj P0;
    public static final sj P1;
    public static final sj P2;
    public static final sj P3;
    public static final sj P4;
    public static final sj P5;
    public static final sj Q;
    public static final sj Q0;
    public static final sj Q1;
    public static final sj Q2;
    public static final sj Q3;
    public static final sj Q4;
    public static final sj Q5;
    public static final sj R;
    public static final sj R0;
    public static final sj R1;
    public static final sj R2;
    public static final sj R3;
    public static final sj R4;
    public static final sj R5;
    public static final sj S;
    public static final sj S0;
    public static final sj S1;
    public static final sj S2;
    public static final sj S3;
    public static final sj S4;
    public static final sj S5;
    public static final sj T;
    public static final sj T0;
    public static final sj T1;
    public static final sj T2;
    public static final sj T3;
    public static final sj T4;
    public static final sj T5;
    public static final sj U;
    public static final sj U0;
    public static final sj U1;
    public static final sj U2;
    public static final sj U3;
    public static final sj U4;
    public static final sj U5;
    public static final sj V;
    public static final sj V0;
    public static final sj V1;
    public static final sj V2;
    public static final sj V3;
    public static final sj V4;
    public static final sj V5;
    public static final sj W;
    public static final sj W0;
    public static final sj W1;
    public static final sj W2;
    public static final sj W3;
    public static final sj W4;
    public static final sj W5;
    public static final sj X;
    public static final sj X0;
    public static final sj X1;
    public static final sj X2;
    public static final sj X3;
    public static final sj X4;
    public static final sj X5;
    public static final sj Y;
    public static final sj Y0;
    public static final sj Y1;
    public static final sj Y2;
    public static final sj Y3;
    public static final sj Y4;
    public static final sj Y5;
    public static final sj Z;
    public static final sj Z0;
    public static final sj Z1;
    public static final sj Z2;
    public static final sj Z3;
    public static final sj Z4;
    public static final sj Z5;
    public static final sj a0;
    public static final sj a1;
    public static final sj a2;
    public static final sj a3;
    public static final sj a4;
    public static final sj a5;
    public static final sj a6;
    public static final sj b0;
    public static final sj b1;
    public static final sj b2;
    public static final sj b3;
    public static final sj b4;
    public static final sj b5;
    public static final sj b6;
    public static final sj c0;
    public static final sj c1;
    public static final sj c2;
    public static final sj c3;
    public static final sj c4;
    public static final sj c5;
    public static final sj c6;
    public static final sj d0;
    public static final sj d1;
    public static final sj d2;
    public static final sj d3;
    public static final sj d4;
    public static final sj d5;
    public static final sj d6;
    public static final sj e0;
    public static final sj e1;
    public static final sj e2;
    public static final sj e3;
    public static final sj e4;
    public static final sj e5;
    public static final sj e6;
    public static final sj f;
    public static final sj f0;
    public static final sj f1;
    public static final sj f2;
    public static final sj f3;
    public static final sj f4;
    public static final sj f5;
    public static final sj f6;
    public static final sj g;
    public static final sj g0;
    public static final sj g1;
    public static final sj g2;
    public static final sj g3;
    public static final sj g4;
    public static final sj g5;
    public static final sj g6;
    public static final sj h;
    public static final sj h0;
    public static final sj h1;
    public static final sj h2;
    public static final sj h3;
    public static final sj h4;
    public static final sj h5;
    public static final sj h6;
    public static final sj i;
    public static final sj i0;
    public static final sj i1;
    public static final sj i2;
    public static final sj i3;
    public static final sj i4;
    public static final sj i5;
    public static final sj i6;
    public static final sj j;
    public static final sj j0;
    public static final sj j1;
    public static final sj j2;
    public static final sj j3;
    public static final sj j4;
    public static final sj j5;
    public static final sj j6;
    public static final sj k;
    public static final sj k0;
    public static final sj k1;
    public static final sj k2;
    public static final sj k3;
    public static final sj k4;
    public static final sj k5;
    public static final sj k6;
    public static final sj l;
    public static final sj l0;
    public static final sj l1;
    public static final sj l2;
    public static final sj l3;
    public static final sj l4;
    public static final sj l5;
    public static final sj l6;
    public static final sj m;
    public static final sj m0;
    public static final sj m1;
    public static final sj m2;
    public static final sj m3;
    public static final sj m4;
    public static final sj m5;
    public static final sj m6;
    public static final sj n;
    public static final sj n0;
    public static final sj n1;
    public static final sj n2;
    public static final sj n3;
    public static final sj n4;
    public static final sj n5;
    public static final sj n6;
    public static final sj o;
    public static final sj o0;
    public static final sj o1;
    public static final sj o2;
    public static final sj o3;
    public static final sj o4;
    public static final sj o5;
    public static final sj o6;
    public static final sj p;
    public static final sj p0;
    public static final sj p1;
    public static final sj p2;
    public static final sj p3;
    public static final sj p4;
    public static final sj p5;
    public static final sj p6;
    public static final sj q;
    public static final sj q0;
    public static final sj q1;
    public static final sj q2;
    public static final sj q3;
    public static final sj q4;
    public static final sj q5;
    public static final sj q6;
    public static final sj r;
    public static final sj r0;
    public static final sj r1;
    public static final sj r2;
    public static final sj r3;
    public static final sj r4;
    public static final sj r5;
    public static final sj r6;
    public static final sj s;
    public static final sj s0;
    public static final sj s1;
    public static final sj s2;
    public static final sj s3;
    public static final sj s4;
    public static final sj s5;
    public static final sj s6;
    public static final sj t;
    public static final sj t0;
    public static final sj t1;
    public static final sj t2;
    public static final sj t3;
    public static final sj t4;
    public static final sj t5;
    public static final sj t6;
    public static final sj u;
    public static final sj u0;
    public static final sj u1;
    public static final sj u2;
    public static final sj u3;
    public static final sj u4;
    public static final sj u5;
    public static final sj u6;
    public static final sj v;
    public static final sj v0;
    public static final sj v1;
    public static final sj v2;
    public static final sj v3;
    public static final sj v4;
    public static final sj v5;
    public static final sj v6;
    public static final sj w;
    public static final sj w0;
    public static final sj w1;
    public static final sj w2;
    public static final sj w3;
    public static final sj w4;
    public static final sj w5;
    public static final sj w6;
    public static final sj x;
    public static final sj x0;
    public static final sj x1;
    public static final sj x2;
    public static final sj x3;
    public static final sj x4;
    public static final sj x5;
    public static final sj x6;
    public static final sj y;
    public static final sj y0;
    public static final sj y1;
    public static final sj y2;
    public static final sj y3;
    public static final sj y4;
    public static final sj y5;
    public static final sj y6;
    public static final sj z;
    public static final sj z0;
    public static final sj z1;
    public static final sj z2;
    public static final sj z3;
    public static final sj z4;
    public static final sj z5;
    public static final sj z6;
    private final String a;
    private final Object b;
    private static final List c = Arrays.asList(Boolean.class, Float.class, Double.class, Integer.class, Long.class, String.class);
    private static final Map d = new HashMap(512);

    public static Collection c() {
        return Collections.synchronizedCollection(d.values());
    }

    static {
        Boolean bool = Boolean.FALSE;
        f = a("is_disabled", bool);
        g = a("device_id", "");
        Boolean bool2 = Boolean.TRUE;
        h = a("rss", bool2);
        i = a("rssoitf", bool);
        j = a("cpoitf", bool);
        k = a("device_token", "");
        l = a("is_verbose_logging", bool);
        m = a("sc", "");
        n = a("sc2", "");
        o = a("sc3", "");
        p = a("server_installed_at", "");
        q = a("pnrc", bool);
        r = a("clear_completion_callback_on_failure", bool);
        s = a("sicd_ms", 0L);
        t = a("logcat_max_line_size", 1000);
        u = a("exception_handler_enabled", bool2);
        v = a(org.json.md.s, "");
        w = a("ps_atu", "");
        x = a("lsu", bool);
        y = a("tla_ms", -1L);
        z = a("stwr", bool);
        A = a("rheinm", bool);
        B = a("uactlac", bool);
        C = a("vsk", bool);
        D = a("error_reporter_v1_sample_percent", 100);
        E = a("health_events_reporter_v1_endpoint", "https://sts.applovin.com/v1/stats/sdk");
        F = a("health_events_reporter_v1_event_level_sampling_percentages", "");
        Float fValueOf = Float.valueOf(-1.0f);
        G = a("health_events_reporter_v1_ad_sampling_percent", fValueOf);
        H = a("health_events_reporter_v1_error_sampling_percent", fValueOf);
        I = a("health_events_reporter_v1_user_session_sampling_percent", fValueOf);
        J = a("health_events_reporter_v1_sampling_percent", Float.valueOf(1.0f));
        K = a("health_events_reporter_v1_batch_grouped_events", bool);
        L = a("health_events_reporter_should_skip_al_events_in_max", bool);
        M = a("health_events_reporter_valid_network_status_codes", "");
        N = a("health_events_reporter_include_cached_asset_info", bool);
        O = a("health_events_reporter_include_html_source", bool);
        P = a("stps", 2);
        Q = a("auxiliary_operations_threads", 1);
        R = a("apsobt", bool2);
        S = a("tmtp", 1);
        T = a("network_thread_count", 2);
        U = a("ntp", 5);
        V = a("ueq", bool);
        W = a("coretc", 1);
        X = a("cachetc", 1);
        Y = a("mtc", 1);
        Z = a("ttc", 1);
        a0 = a("otc", 1);
        b0 = a("uaeq", bool);
        c0 = a("ah_cvc", bool2);
        d0 = a("ah_cdde", bool2);
        e0 = a("ah_crut", bool2);
        f0 = a("init_omsdk", bool2);
        g0 = a("omsdk_partner_name", "applovin");
        TimeUnit timeUnit = TimeUnit.SECONDS;
        h0 = a("ttc_max_click_duration_ms", Long.valueOf(timeUnit.toMillis(1L)));
        i0 = a("ttc_max_click_distance_dp", 10);
        AppLovinTouchToClickListener.ClickRecognitionState clickRecognitionState = AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN;
        j0 = a("ttc_acrsv2a", Integer.valueOf(clickRecognitionState.ordinal()));
        k0 = a("ttc_acrsnv", Integer.valueOf(clickRecognitionState.ordinal()));
        l0 = a("ttc_acrsa", Integer.valueOf(clickRecognitionState.ordinal()));
        m0 = a("ttc_acrsn", Integer.valueOf(clickRecognitionState.ordinal()));
        n0 = a("ttc_edge_buffer_dp", 0);
        o0 = a("whitelisted_postback_endpoints", "https://prod-a.applovin.com,https://rt.applovin.com/4.0/pix, https://rt.applvn.com/4.0/pix,https://ms.applovin.com/,https://ms.applvn.com/");
        p0 = a("fetch_settings_endpoint", "https://ms.applovin.com/");
        q0 = a("fetch_settings_backup_endpoint", "https://ms.applvn.com/");
        r0 = a("adserver_endpoint", "https://a.applovin.com/");
        s0 = a("adserver_backup_endpoint", "https://a.applvn.com/");
        t0 = a("api_endpoint", "https://d.applovin.com/");
        u0 = a("api_backup_endpoint", "https://d.applvn.com/");
        v0 = a("event_tracking_endpoint_v2", "https://rt.applovin.com/");
        w0 = a("event_tracking_backup_endpoint_v2", "https://rt.applvn.com/");
        x0 = a("webview_network_error_endpoints_to_report", "applovin.com,applvn.com");
        y0 = a("token_type_prefixes_r", "4!");
        z0 = a("token_type_prefixes_arj", "json_v3!");
        A0 = a("top_level_events", "landing,paused,resumed,cf_start,tos_ok,gdpr_ok,ref,rdf,checkout,iap");
        TimeUnit timeUnit2 = TimeUnit.DAYS;
        B0 = a("cache_file_ttl_seconds", Long.valueOf(timeUnit2.toSeconds(1L)));
        C0 = a("cache_max_size_mb", -1);
        D0 = a("precache_delimiters", ")]', ");
        E0 = a("ad_resource_caching_enabled", bool2);
        F0 = a("resource_cache_prefix", "https://vid.applovin.com/,https://stage-vid.applovin.com/,https://pdn.applovin.com/,https://stage-pdn.applovin.com/,https://img.applovin.com/,https://stage-img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://stage-assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://stage-vid.applovin.com/,http://pdn.applovin.com/,http://stage-pdn.applovin.com/,http://img.applovin.com/,http://stage-img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://stage-assets.applovin.com/,http://cdnjs.cloudflare.com/,http://u.appl.vn/,https://u.appl.vn/,https://res.applovin.com/,https://res1.applovin.com/,https://res2.applovin.com/,https://res3.applovin.com/,http://res.applovin.com/,http://res1.applovin.com/,http://res2.applovin.com/,http://res3.applovin.com/");
        G0 = a("preserved_cached_assets", "sound_off.png,sound_on.png,closeOptOut.png,1381250003_28x28.png,zepto-1.1.3.min.js,jquery-2.1.1.min.js,jquery-1.9.1.min.js,jquery.knob.js");
        H0 = a("resource_max_filename_length", 255);
        I0 = a("ccrc", bool);
        J0 = a("mcct", 3);
        K0 = a("mchct", 3);
        L0 = a("dfirf", bool);
        M0 = a("dfipf", bool);
        N0 = a("decr", bool);
        O0 = a("dcrome", bool);
        P0 = a("dcrobs", bool);
        Q0 = a("lfeufc", bool);
        R0 = a("pcro", bool);
        S0 = a("efecobt", bool);
        T0 = a("serfaad", bool);
        U0 = a("mdafra", 1);
        V0 = a("ssch", bool2);
        W0 = a("suaf", bool);
        X0 = a("lfblrs", bool);
        Y0 = a("ape", bool);
        Z0 = a("pafqi", bool);
        TimeUnit timeUnit3 = TimeUnit.MINUTES;
        a1 = a("pae_ms", Long.valueOf(timeUnit3.toMillis(5L)));
        b1 = a("pamttl_ms", Long.valueOf(timeUnit.toMillis(5L)));
        c1 = a("saewib", bool);
        d1 = a("fsae_ms", -1L);
        e1 = a("raae", bool);
        f1 = a("vr_retry_count_v1", 1);
        g1 = a("cr_retry_count_v1", 1);
        h1 = a("text_incent_warning_title", "Attention!");
        i1 = a("text_incent_warning_body", "You won’t get your reward if the video hasn’t finished.");
        j1 = a("text_incent_warning_close_option", "Close");
        k1 = a("text_incent_warning_continue_option", "Keep Watching");
        l1 = a("text_incent_nonvideo_warning_title", "Attention!");
        m1 = a("text_incent_nonvideo_warning_body", "You won’t get your reward if the game hasn’t finished.");
        n1 = a("text_incent_nonvideo_warning_close_option", "Close");
        o1 = a("text_incent_nonvideo_warning_continue_option", "Keep Playing");
        p1 = a("close_button_touch_area", 0);
        q1 = a("close_button_outside_touch_area", 0);
        r1 = a("creative_debugger_enabled", bool2);
        s1 = a("smdfhcdb", bool2);
        t1 = a("adview_clearview", bool);
        u1 = a("ravip", bool);
        v1 = a("viewability_adview_imp_delay_ms", Long.valueOf(timeUnit.toMillis(1L)));
        w1 = a("viewability_adview_banner_min_width", 320);
        x1 = a("viewability_adview_banner_min_height", Integer.valueOf(AppLovinAdSize.BANNER.getHeight()));
        MaxAdFormat maxAdFormat = MaxAdFormat.MREC;
        y1 = a("viewability_adview_mrec_min_width", Integer.valueOf(maxAdFormat.getSize().getWidth()));
        z1 = a("viewability_adview_mrec_min_height", Integer.valueOf(maxAdFormat.getSize().getHeight()));
        A1 = a("viewability_adview_leader_min_width", 728);
        B1 = a("viewability_adview_leader_min_height", Integer.valueOf(AppLovinAdSize.LEADER.getHeight()));
        C1 = a("viewability_adview_native_min_width", 0);
        D1 = a("viewability_adview_native_min_height", 0);
        E1 = a("viewability_adview_min_alpha", Float.valueOf(10.0f));
        F1 = a("viewability_timer_min_visible_ms", Long.valueOf(timeUnit.toMillis(1L)));
        G1 = a("viewability_timer_interval_ms", 100L);
        H1 = a("expandable_close_button_size", 27);
        I1 = a("expandable_h_close_button_margin", 10);
        J1 = a("expandable_t_close_button_margin", 10);
        K1 = a("expandable_lhs_close_button", bool);
        L1 = a("expandable_close_button_touch_area", 0);
        M1 = a("iaad", bool);
        N1 = a("js_tag_schemes", "applovin,mopub");
        O1 = a("js_tag_load_success_hosts", "load,load_succeeded");
        P1 = a("js_tag_load_failure_hosts", "failLoad,load_failed");
        Q1 = a("fullscreen_ad_pending_display_state_timeout_ms", Long.valueOf(timeUnit.toMillis(10L)));
        R1 = a("fullscreen_ad_showing_state_timeout_ms", Long.valueOf(timeUnit3.toMillis(2L)));
        S1 = a("lhs_close_button_video", bool);
        T1 = a("close_button_right_margin_video", 4);
        U1 = a("close_button_size_video", 30);
        V1 = a("close_button_top_margin_video", 8);
        W1 = a("video_countdown_clock_margin", 10);
        X1 = a("video_countdown_clock_gravity", 83);
        Y1 = a("countdown_clock_size", 32);
        Z1 = a("countdown_clock_stroke_size", 4);
        a2 = a("countdown_clock_text_size", 28);
        b2 = a("draw_countdown_clock", bool2);
        c2 = a("inter_display_delay", 200L);
        d2 = a("maximum_close_button_delay_seconds", 999L);
        e2 = a("respect_close_button", bool2);
        f2 = a("lhs_skip_button", bool2);
        g2 = a("track_app_killed", bool);
        h2 = a("track_ad_duration", bool);
        i2 = a("track_ad_duration_interval_ms", Long.valueOf(timeUnit.toMillis(1L)));
        j2 = a("simplified_app_killed_detection", bool);
        k2 = a("app_closed_time_threshold_for_app_killed_event_ms", Long.valueOf(timeUnit.toMillis(60L)));
        l2 = a("mute_controls_enabled", bool);
        m2 = a("allow_user_muting", bool2);
        n2 = a("mute_videos", bool);
        o2 = a("show_mute_by_default", bool);
        p2 = a("mute_with_user_settings", bool2);
        q2 = a("mute_button_size", 32);
        r2 = a("mute_button_margin", 10);
        s2 = a("mute_button_gravity", 85);
        t2 = a("progress_bar_step", 25L);
        u2 = a("progress_bar_scale", 10000);
        v2 = a("progress_bar_vertical_padding", -8);
        w2 = a("vs_buffer_indicator_size", 50);
        x2 = a("video_zero_length_as_computed", bool);
        y2 = a("set_poststitial_muted_initial_delay_ms", 500L);
        z2 = a("fasuic", bool2);
        A2 = a("fsahrpg", bool2);
        B2 = a("eaafrwsoa", bool2);
        C2 = a("postitial_progress_bar_step_ms", 25L);
        D2 = a("postitial_progress_bar_on_bottom", bool2);
        E2 = a("postitial_progress_bar_vertical_padding", -8);
        F2 = a("postitial_progress_bar_scale", 10000);
        G2 = a("fahosu", bool);
        H2 = a("ignored_exoplayer_media_errors", "Player release timed out");
        I2 = a("nsuttcl", bool);
        J2 = a("submit_postback_timeout", Integer.valueOf((int) timeUnit.toMillis(10L)));
        K2 = a("submit_postback_retries", 4);
        L2 = a("max_postback_attempts", 3);
        M2 = a("max_persisted_postbacks", 100);
        N2 = a("submit_web_tracker_timeout", Integer.valueOf((int) timeUnit.toMillis(7L)));
        O2 = a("sossp", bool);
        P2 = a("spp", bool2);
        Q2 = a("fire_native_ad_postbacks_from_webview", bool);
        R2 = a("use_requests_for_native_ad_click_postbacks", bool);
        S2 = a("preload_postback_webview", bool);
        T2 = a("get_retry_delay_v1", Integer.valueOf((int) timeUnit.toMillis(10L)));
        U2 = a("http_connection_timeout", Integer.valueOf((int) timeUnit.toMillis(30L)));
        V2 = a("http_socket_timeout", Integer.valueOf((int) timeUnit.toMillis(20L)));
        W2 = a("force_ssl", bool);
        X2 = a("fetch_ad_connection_timeout", Integer.valueOf((int) timeUnit.toMillis(30L)));
        Y2 = a("fetch_ad_retry_count_v1", 1);
        Z2 = a("faer", bool);
        a3 = a("faroae", bool);
        b3 = a("submit_data_retry_count_v1", 1);
        c3 = a("response_buffer_size", 16000);
        d3 = a("fetch_basic_settings_connection_timeout_ms", Integer.valueOf((int) timeUnit.toMillis(10L)));
        e3 = a("fetch_basic_settings_retry_count", 3);
        f3 = a("fetch_basic_settings_on_reconnect", bool);
        g3 = a("skip_fetch_basic_settings_if_not_connected", bool);
        h3 = a("fetch_basic_settings_retry_delay_ms", Integer.valueOf((int) timeUnit.toMillis(2L)));
        i3 = a("idflrwbe", bool);
        j3 = a("falawpr", bool);
        k3 = a("sort_query_parameters", bool);
        l3 = a("communicator_request_timeout_ms", Long.valueOf(timeUnit.toMillis(10L)));
        m3 = a("communicator_request_retry_count", 3);
        n3 = a("communicator_request_retry_delay_ms", Long.valueOf(timeUnit.toMillis(2L)));
        o3 = a("rfbsd_ms", -1L);
        p3 = a("ehkpd_ms", 500L);
        q3 = a("rironc", bool);
        r3 = a("rroncbd", bool);
        s3 = a("wverc_ms", Long.valueOf(timeUnit.toMillis(5L)));
        t3 = a("sducifm", bool);
        u3 = a("ad_session_minutes", 60);
        v3 = a("session_tracking_cooldown_on_event_fire", bool2);
        w3 = a("session_tracking_resumed_cooldown_minutes", 90L);
        x3 = a("session_tracking_paused_cooldown_minutes", 90L);
        y3 = a("qq", bool);
        z3 = a("qq1", bool2);
        A3 = a("qq2", bool2);
        B3 = a("qq3", bool2);
        C3 = a("qq4", bool2);
        D3 = a("qq5", bool2);
        E3 = a("qq6", bool2);
        F3 = a("qq7", bool2);
        G3 = a("qq8", bool2);
        H3 = a("qq9", bool);
        I3 = a("qq10", bool2);
        J3 = a("pui", bool2);
        K3 = a("plugin_version", "");
        L3 = a("validate_admob_adapter_sdk_version", bool2);
        M3 = a("ccbtbsic", bool);
        N3 = a("hgn", bool2);
        O3 = a("cso", bool2);
        P3 = a("cfs", bool2);
        Q3 = a("cmi", bool2);
        R3 = a("crat", bool2);
        S3 = a("cvs", bool2);
        T3 = a("caf", bool2);
        U3 = a("cf", bool2);
        V3 = a("cmtl", bool2);
        W3 = a("cnr", bool2);
        X3 = a("ccr", bool);
        Y3 = a("adr", bool2);
        Z3 = a("volume_normalization_factor", Float.valueOf(6.6666665f));
        a4 = a("system_user_agent_collection_enabled", bool);
        b4 = a("user_agent_collection_enabled", bool);
        c4 = a("user_agent_caching_enabled", bool2);
        d4 = a("collect_device_angle", bool2);
        e4 = a("collect_device_movement", bool2);
        f4 = a("cipc", bool2);
        g4 = a("movement_degradation", Float.valueOf(0.75f));
        h4 = a("device_sensor_period_ms", Integer.valueOf(IronSourceConstants.INTERSTITIAL_DAILY_CAPPED));
        i4 = a("idcw", bool);
        j4 = a("fetch_basic_settings_delay_ms", 1500);
        k4 = a("mps", "");
        l4 = a("mpsl", 3);
        m4 = a(org.json.xm.c, "com.applovin,dalvik,java,android,com.android");
        n4 = a("cmps", bool);
        o4 = a("rmps", bool);
        p4 = a("collect_webview_package_info", bool);
        q4 = a("webview_package_names", "com.google.android.webview,com.android.webview");
        r4 = a("collect_opengl_version", bool);
        s4 = a("ncre", bool);
        t4 = a("ncrs", "4,5,6,7,8,11,16");
        u4 = a("ncrcs", bool);
        v4 = a("dcttl_1_seconds", 5);
        w4 = a("dcttl_2_seconds", 30);
        x4 = a("dcttl_3_seconds", Integer.valueOf((int) timeUnit3.toSeconds(1L)));
        y4 = a("dcttl_4_seconds", Integer.valueOf((int) timeUnit3.toSeconds(30L)));
        z4 = a("dcttl_5_seconds", Integer.valueOf((int) TimeUnit.HOURS.toSeconds(1L)));
        A4 = a("dcttl_6_seconds", Integer.valueOf((int) timeUnit2.toSeconds(1L)));
        B4 = a("is_track_ad_info", bool2);
        C4 = a("umsm", bool);
        D4 = a("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
        E4 = a("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
        F4 = a("vast_max_response_length", 640000);
        G4 = a("vast_max_wrapper_depth", 5);
        H4 = a("vast_unsupported_video_extensions", "ogv,flv");
        I4 = a("vast_unsupported_video_types", "video/ogg,video/x-flv");
        J4 = a("vast_validate_with_extension_if_no_video_type", bool2);
        K4 = a("vast_wrapper_resolution_retry_count_v1", 1);
        L4 = a("vast_wrapper_resolution_connection_timeout", Integer.valueOf((int) timeUnit.toMillis(30L)));
        M4 = a("vast_industry_icon_max_size", 20);
        N4 = a("vast_industry_icon_margin", 12);
        O4 = a("vast_industry_icon_gravity", 85);
        P4 = a("vast_native_mute_button_size", 24);
        Q4 = a("vast_native_play_pause_button_size", 24);
        R4 = a("vast_native_video_widget_padding", 6);
        S4 = a("vast_native_video_widget_alpha", Float.valueOf(0.5f));
        T4 = a("vast_native_video_widgets_enabled", bool2);
        U4 = a("vast_replay_video_upon_completion", bool2);
        V4 = a("vast_replay_icon_size", 64);
        W4 = a("vcjfhr", bool);
        X4 = a("vast_untracked_exoplayer_media_errors", "Player release timed out");
        Y4 = a("vcjfhrr", "(?:<|%3C)script[^>]*src=\"(https[^\"]*\\.js[^\"]*)\".*?(?:>|%3E)");
        Z4 = a("vpenfxr", "(<Error><!\\[CDATA\\[[^>]*><\\/Error>)");
        a5 = a("ree", bool2);
        vi.a aVar = vi.a.DEFAULT;
        b5 = a("ree_t", Integer.valueOf(aVar.b()));
        c5 = a("btee", bool2);
        d5 = a("btet", Integer.valueOf(aVar.b()));
        e5 = a("reetoa", bool);
        f5 = a("reet_msfs", Integer.valueOf(aVar.b()));
        g5 = a("reet_msma", Integer.valueOf(vi.a.V2.b()));
        h5 = a("reet_msmd", Integer.valueOf(aVar.b()));
        i5 = a("reet_asfp", Integer.valueOf(aVar.b()));
        j5 = a("reet_asfg", Integer.valueOf(aVar.b()));
        k5 = a("reet_aset", Integer.valueOf(aVar.b()));
        l5 = a("reet_esdi", Integer.valueOf(aVar.b()));
        m5 = a("reet_esrp", Integer.valueOf(aVar.b()));
        n5 = a("apdra", bool);
        o5 = a("apdrfs", bool);
        p5 = a("apdrma", bool);
        q5 = a("apdrmd", bool);
        r5 = a("apdrfa", bool);
        s5 = a("apdrev", bool);
        t5 = a("apdrdi", bool);
        u5 = a("apdrrp", bool);
        v5 = a("server_timestamp_ms", 0L);
        w5 = a("device_timestamp_ms", 0L);
        x5 = a("gzip_min_length", 0);
        y5 = a("gzip_encoding_default", bool);
        z5 = a("fetch_settings_gzip", bool);
        A5 = a("device_init_gzip", bool);
        B5 = a("fetch_ad_gzip", bool);
        C5 = a("event_tracking_gzip", bool);
        D5 = a("reward_postback_gzip", bool);
        E5 = a("handle_render_process_gone", bool2);
        F5 = a("rworpg", bool2);
        G5 = a("fdadaomr", bool2);
        H5 = a("vfswccar", bool);
        I5 = a("sparafad", bool);
        J5 = a("teorpc", bool);
        K5 = a("set_webview_render_process_client", bool);
        L5 = a("disable_webview_hardware_acceleration", bool);
        M5 = a("anr_detection_enabled", bool);
        N5 = a("anr_trigger_millis", 4000L);
        O5 = a("anr_touch_millis", 3000L);
        P5 = a("anr_check_millis", 3000L);
        Q5 = a("uobid", bool2);
        R5 = a("bvde", bool);
        S5 = a("bvdidm", 1000L);
        T5 = a("bvdim", 4000L);
        U5 = a("bvdrs", 10);
        V5 = a("bvdct", 230);
        W5 = a("bvdict", 3);
        X5 = a("bvad", bool);
        Y5 = a("bvebb", bool2);
        Z5 = a("bvscb", bool2);
        a6 = a("bvlmtb", -1L);
        b6 = a("dwvvb", bool);
        c6 = a("stcpc", bool2);
        d6 = a("stcic", bool2);
        e6 = a("qjscwwvl", bool);
        f6 = a("web_contents_debugging_enabled", bool);
        g6 = a("fcioiauiidb", bool2);
        h6 = a("teouauiidb", bool2);
        i6 = a("usc", bool);
        j6 = a("should_apply_web_view_settings_to_web_view_button", bool);
        k6 = a("should_check_for_play_store_disabled_before_launching_click", bool);
        l6 = a("should_use_cached_screen_size_for_foldable_devices", bool2);
        m6 = a("config_consent_dialog_state", "unknown");
        n6 = a("country_code", "");
        o6 = a("consent_flow_doc_url", "https://developers.applovin.com/en/android/overview/terms-and-privacy-policy-flow");
        p6 = a("consent_flow_unity_doc_url", "https://developers.applovin.com/en/unity/overview/terms-and-privacy-policy-flow");
        q6 = a("cfadtml", 20);
        r6 = a("enable_custom_tabs_service", bool2);
        s6 = a("custom_tabs_chrome_package_names", "com.android.chrome");
        t6 = a("custom_tabs_prefer_default_browser", bool2);
        u6 = a("custom_tabs_animation_enabled", bool2);
        v6 = a("ps_etr", bool);
        w6 = a("ps_tri_ms", Long.valueOf(timeUnit2.toMillis(7L)));
        x6 = a("ps_ftri_ms", -1L);
        y6 = a("ps_sroftr", bool);
        z6 = a("ps_sroftrof", bool);
        A6 = a("gawvbu", "https://applovin.com");
        B6 = a("communicator_enabled", bool2);
        C6 = a("adse", bool2);
    }

    public sj(String str, Object obj) {
        if (str == null) {
            throw new IllegalArgumentException("No name specified");
        }
        if (obj != null) {
            this.a = str;
            this.b = obj;
            return;
        }
        throw new IllegalArgumentException("No default value specified");
    }

    public String b() {
        return this.a;
    }

    public Object a(Object obj) {
        return this.b.getClass().cast(obj);
    }

    @Override // java.lang.Comparable
    public int compareTo(Object obj) {
        if (!(obj instanceof sj)) {
            return 0;
        }
        return this.a.compareTo(((sj) obj).b());
    }

    public Object a() {
        return this.b;
    }

    protected static sj a(String str, Object obj) {
        if (obj != null) {
            if (c.contains(obj.getClass())) {
                sj sjVar = new sj(str, obj);
                Map map = d;
                if (!map.containsKey(str)) {
                    map.put(str, sjVar);
                    return sjVar;
                }
                throw new IllegalArgumentException("Setting has already been used: " + str);
            }
            throw new IllegalArgumentException("Unsupported value type: " + obj.getClass());
        }
        throw new IllegalArgumentException("No default value specified");
    }
}
