package com.applovin.impl;

import java.util.Arrays;
import java.util.concurrent.TimeUnit;

/* JADX INFO: loaded from: classes.dex */
public abstract class ue extends sj {
    public static final sj A7;
    public static final sj B7;
    public static final sj C7;
    public static final sj D6 = sj.a("afi", "");
    public static final sj D7;
    public static final sj E6;
    public static final sj E7;
    public static final sj F6;
    public static final sj F7;
    public static final sj G6;
    public static final sj G7;
    public static final sj H6;
    public static final sj H7;
    public static final sj I6;
    public static final sj I7;
    public static final sj J6;
    public static final sj J7;
    public static final sj K6;
    public static final sj K7;
    public static final sj L6;
    public static final sj L7;
    public static final sj M6;
    public static final sj M7;
    public static final sj N6;
    public static final sj N7;
    public static final sj O6;
    public static final sj O7;
    public static final sj P6;
    public static final sj Q6;
    public static final sj R6;
    public static final sj S6;
    public static final sj T6;
    public static final sj U6;
    public static final sj V6;
    public static final sj W6;
    public static final sj X6;
    public static final sj Y6;
    public static final sj Z6;
    public static final sj a7;
    public static final sj b7;
    public static final sj c7;
    public static final sj d7;
    public static final sj e7;
    public static final sj f7;
    public static final sj g7;
    public static final sj h7;
    public static final sj i7;
    public static final sj j7;
    public static final sj k7;
    public static final sj l7;
    public static final sj m7;
    public static final sj n7;
    public static final sj o7;
    public static final sj p7;
    public static final sj q7;
    public static final sj r7;
    public static final sj s7;
    public static final sj t7;
    public static final sj u7;
    public static final sj v7;
    public static final sj w7;
    public static final sj x7;
    public static final sj y7;
    public static final sj z7;

    static {
        TimeUnit timeUnit = TimeUnit.SECONDS;
        E6 = sj.a("afi_ms", Long.valueOf(timeUnit.toMillis(5L)));
        F6 = sj.a("mediation_endpoint", "https://ms.applovin.com/");
        G6 = sj.a("mediation_backup_endpoint", "https://ms.applvn.com/");
        H6 = sj.a("fetch_next_ad_retry_delay_ms", Long.valueOf(timeUnit.toMillis(2L)));
        I6 = sj.a("fetch_next_ad_timeout_ms", Long.valueOf(timeUnit.toMillis(30L)));
        J6 = sj.a("fetch_mediation_debugger_info_timeout_ms", Long.valueOf(timeUnit.toMillis(7L)));
        Boolean bool = Boolean.TRUE;
        K6 = sj.a("auto_init_mediation_debugger", bool);
        L6 = sj.a("postback_macros", "{\"{MCODE}\":\"mcode\",\"{BCODE}\":\"bcode\",\"{ICODE}\":\"icode\",\"{SCODE}\":\"scode\"}");
        M6 = sj.a("max_signal_provider_latency_ms", Long.valueOf(timeUnit.toMillis(30L)));
        N6 = sj.a("default_adapter_timeout_ms", Long.valueOf(timeUnit.toMillis(10L)));
        O6 = sj.a("ad_refresh_ms", Long.valueOf(timeUnit.toMillis(30L)));
        P6 = sj.a("ad_load_failure_refresh_ms", Long.valueOf(timeUnit.toMillis(30L)));
        Q6 = sj.a("ad_load_failure_refresh_ignore_error_codes", "204");
        R6 = sj.a("refresh_ad_on_app_resume_elapsed_threshold_ms", 0L);
        S6 = sj.a("refresh_ad_view_timer_responds_to_background", bool);
        T6 = sj.a("refresh_ad_view_timer_responds_to_store_kit", bool);
        Boolean bool2 = Boolean.FALSE;
        U6 = sj.a("refresh_ad_view_timer_responds_to_window_visibility_changed", bool2);
        V6 = sj.a("avrsponse", bool2);
        W6 = sj.a("allow_pause_auto_refresh_immediately", bool2);
        X6 = sj.a("ad_view_race_condition_fix_enabled", bool2);
        Y6 = sj.a("fullscreen_display_delay_ms", 0L);
        Z6 = sj.a("susaode", bool2);
        a7 = sj.a("ahdm", 500L);
        b7 = sj.a("ad_view_refresh_precache_request_viewability_undesired_flags", 246L);
        c7 = sj.a("ad_view_refresh_precache_request_enabled", bool);
        d7 = sj.a("famttl_ms", 0L);
        e7 = sj.a("signal_expiration_ms", -1L);
        f7 = sj.a("signal_cache_level", Integer.valueOf(xj.b.AD_FORMAT.ordinal()));
        TimeUnit timeUnit2 = TimeUnit.HOURS;
        g7 = sj.a("ad_expiration_ms", Long.valueOf(timeUnit2.toMillis(4L)));
        h7 = sj.a("native_ad_expiration_ms", Long.valueOf(timeUnit2.toMillis(4L)));
        i7 = sj.a("rena", bool);
        j7 = sj.a("fullscreen_ad_displayed_timeout_ms", -1L);
        k7 = sj.a("freast_ms", -1L);
        l7 = sj.a("ad_hidden_timeout_ms", -1L);
        m7 = sj.a("schedule_ad_hidden_on_ad_dismiss", bool2);
        n7 = sj.a("schedule_ad_hidden_on_single_task_app_relaunch", bool2);
        o7 = sj.a("ad_hidden_on_ad_dismiss_callback_delay_ms", Long.valueOf(timeUnit.toMillis(1L)));
        p7 = sj.a("proe", bool2);
        q7 = sj.a("mute_state", 2);
        r7 = sj.a("saf", "");
        s7 = sj.a("saui", "");
        t7 = sj.a("mra", -1);
        u7 = sj.a("mra_af", "INTER,REWARDED,REWARDED_INTER,BANNER,LEADER,MREC");
        v7 = sj.a("svadfr", bool2);
        w7 = sj.a("fadiafase", bool);
        x7 = sj.a("fadwvcv", bool);
        y7 = sj.a("bfarud", bool2);
        z7 = sj.a("inacc", Boolean.valueOf(yp.b(Arrays.asList("com.textmeinc.textme", "com.textmeinc.freetone", "com.textmeinc.textme3", "com.jaumo", "com.jaumo.casual", "com.pinkapp", "com.jaumo.mature", "com.jaumo.prime", "com.jaumo.gay", "com.jaumo.lesbian"))));
        A7 = sj.a("pbataipaf", "");
        B7 = sj.a("bwt_ms", Long.valueOf(timeUnit.toMillis(30L)));
        C7 = sj.a("twt_ms", Long.valueOf(timeUnit.toMillis(30L)));
        D7 = sj.a("adiets_sec", Long.valueOf(TimeUnit.MINUTES.toSeconds(1L)));
        E7 = sj.a("faomq", bool2);
        F7 = sj.a("siflcfbt", bool2);
        G7 = sj.a("rahcnct_sec", -1);
        H7 = sj.a("uabta", bool2);
        I7 = sj.a("use_initialization_spec_during_init", bool2);
        J7 = sj.a("use_promises_during_init", bool2);
        K7 = sj.a("report_cimp_after_ierr", bool2);
        L7 = sj.a("fail_collection_for_empty_signal", bool2);
        M7 = sj.a("sdaomq", bool2);
        N7 = sj.a("fetch_mediated_ad_gzip", bool);
        O7 = sj.a("max_postback_gzip", bool);
    }
}
