import frida, pathlib, time, json
dev = frida.get_device_manager().add_remote_device('127.0.0.1:27042')
print('spawn ' + 'com.identityv.shrek156')
pid = dev.spawn(['com.identityv.shrek156'])
print('spawned pid=%d' % pid)
proc = dev.attach(pid)
js = pathlib.Path(r'D:\APK-Reverse\projects\DWRG\work_dwrg\hook_login.js').read_text(encoding='utf-8')
script = proc.create_script(js)
def on_msg(m, d):
    print('[SPAWN_MSG] ' + json.dumps(m, ensure_ascii=False)[:2000])
script.on('message', on_msg)
script.load()
print('loaded, resume')
dev.resume(pid)
time.sleep(20)
print('done')
