package org.json;

/* JADX INFO: loaded from: classes3.dex */
public class rb {
    public static final String A = "callfailreason";
    public static final String B = "timingvalue";
    public static final String C = "inAppBidding";
    public static final String D = "rewarded";
    public static final Object E = "initialized instance";
    public static final Object F = "uninitialized instance";
    public static final String G = "isoneflow";
    public static final String H = "isMultipleAdObjects";
    public static final String I = "custom_c";
    public static final String J = "custom_b";
    public static final String K = "Content-Type";
    public static final String L = "application/json";
    public static final String M = "charset";
    public static final String N = "utf-8";
    public static final String O = "events";
    public static final boolean P = true;
    public static final String Q = "table";
    public static final String R = "supersonic.adunitanalytics.ad_unit_events";
    public static final String S = "data";
    public static final char T = '=';
    public static final String U = "logEvent failed eventsTracker doesn't exist";
    public static final String a = "sdk5Events";
    public static final String b = "sdkversion";
    public static final String c = "n_";
    public static final String d = "bundleid";
    public static final String e = "connectiontype";
    public static final String f = "rawconnectiontype";
    public static final String g = "applicationkey";
    public static final String h = "sessionid";
    public static final String i = "applicationuserid";
    public static final String j = "deviceos";
    public static final String k = "deviceosversion";
    public static final String l = "deviceapilevel";
    public static final String m = "deviceoem";
    public static final String n = "devicemodel";
    public static final String o = "env";
    public static final String p = "origin";
    public static final String q = "n";
    public static final String r = "endpoint";
    public static final String s = "enabled";
    public static final String t = "prod";
    public static final String u = "eventid";
    public static final String v = "demandsourcename";
    public static final String w = "producttype";
    public static final String x = "isbiddinginstance";
    public static final String y = "generalmessage";
    public static final String z = "controllersource";
}
